source "http://ruby.taobao.org"

gem 'bundler'

# Declare your gem's dependencies in rcity.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
gem "jquery-rails"

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
 gem 'mongoid' , "  ~> 2.4.8"


#for development
group :assets do
  gem 'sass-rails', "  ~> 3.2.3"
  gem 'coffee-rails', "~> 3.2.1"
  gem 'uglifier', '>= 1.0.3'
  gem "less" # do not miss this one
end

#copy from Rforum ,remove some not needed
group :development, :test do
  gem 'capistrano', '2.9.0'
  gem 'chunky_png', "1.2.5"
  gem "memcache-client", "1.8.5"
  gem 'progress_bar'
  gem 'rspec-rails', '~> 2.8.1'
  gem 'factory_girl_rails' , '~> 3.0.0'
  gem 'thin'
  gem "simplecov", :require => false
  gem "rspec-cells"
  gem "capybara"
 #gem "sunspot-rails-tester"
  gem 'quiet_assets', :path=>"~/vob/github/quiet_assets" #to disable those annoy assets log
  gem 'guard'
  gem 'guard-rspec'
  gem 'libnotify'
  gem 'spork-rails'
  gem 'guard-spork'
  gem 'guard-livereload'
  gem 'yajl-ruby'
  gem 'launchy'
  gem 'database_cleaner'
end

require 'pathname'
pn = Pathname.new(File.dirname(__FILE__))
vob_path=pn.parent #do we have one line solution?
gem "rtheme" ,:path=>File.join(vob_path,"Rtheme")

#this is ugly
gem 'bootstrap-rails', :require => 'bootstrap-rails',:path=>"~/vob/github/bootstrap-rails"