require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Cpanel::CargoBigCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # Cpanel::CargoBigCategory. As you add validations to Cpanel::CargoBigCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Cpanel::CargoBigCategoriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cpanel_cargo_big_categories as @cpanel_cargo_big_categories" do
      cargo_big_category = Cpanel::CargoBigCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cpanel_cargo_big_categories).should eq([cargo_big_category])
    end
  end

  describe "GET show" do
    it "assigns the requested cargo_big_category as @cargo_big_category" do
      cargo_big_category = Cpanel::CargoBigCategory.create! valid_attributes
      get :show, {:id => cargo_big_category.to_param}, valid_session
      assigns(:cargo_big_category).should eq(cargo_big_category)
    end
  end

  describe "GET new" do
    it "assigns a new cargo_big_category as @cargo_big_category" do
      get :new, {}, valid_session
      assigns(:cargo_big_category).should be_a_new(Cpanel::CargoBigCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested cargo_big_category as @cargo_big_category" do
      cargo_big_category = Cpanel::CargoBigCategory.create! valid_attributes
      get :edit, {:id => cargo_big_category.to_param}, valid_session
      assigns(:cargo_big_category).should eq(cargo_big_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cpanel::CargoBigCategory" do
        expect {
          post :create, {:cargo_big_category => valid_attributes}, valid_session
        }.to change(Cpanel::CargoBigCategory, :count).by(1)
      end

      it "assigns a newly created cargo_big_category as @cargo_big_category" do
        post :create, {:cargo_big_category => valid_attributes}, valid_session
        assigns(:cargo_big_category).should be_a(Cpanel::CargoBigCategory)
        assigns(:cargo_big_category).should be_persisted
      end

      it "redirects to the created cargo_big_category" do
        post :create, {:cargo_big_category => valid_attributes}, valid_session
        response.should redirect_to(Cpanel::CargoBigCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cargo_big_category as @cargo_big_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cpanel::CargoBigCategory.any_instance.stub(:save).and_return(false)
        post :create, {:cargo_big_category => {}}, valid_session
        assigns(:cargo_big_category).should be_a_new(Cpanel::CargoBigCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cpanel::CargoBigCategory.any_instance.stub(:save).and_return(false)
        post :create, {:cargo_big_category => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cargo_big_category" do
        cargo_big_category = Cpanel::CargoBigCategory.create! valid_attributes
        # Assuming there are no other cpanel_cargo_big_categories in the database, this
        # specifies that the Cpanel::CargoBigCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cpanel::CargoBigCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cargo_big_category.to_param, :cargo_big_category => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cargo_big_category as @cargo_big_category" do
        cargo_big_category = Cpanel::CargoBigCategory.create! valid_attributes
        put :update, {:id => cargo_big_category.to_param, :cargo_big_category => valid_attributes}, valid_session
        assigns(:cargo_big_category).should eq(cargo_big_category)
      end

      it "redirects to the cargo_big_category" do
        cargo_big_category = Cpanel::CargoBigCategory.create! valid_attributes
        put :update, {:id => cargo_big_category.to_param, :cargo_big_category => valid_attributes}, valid_session
        response.should redirect_to(cargo_big_category)
      end
    end

    describe "with invalid params" do
      it "assigns the cargo_big_category as @cargo_big_category" do
        cargo_big_category = Cpanel::CargoBigCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cpanel::CargoBigCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => cargo_big_category.to_param, :cargo_big_category => {}}, valid_session
        assigns(:cargo_big_category).should eq(cargo_big_category)
      end

      it "re-renders the 'edit' template" do
        cargo_big_category = Cpanel::CargoBigCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cpanel::CargoBigCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => cargo_big_category.to_param, :cargo_big_category => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cargo_big_category" do
      cargo_big_category = Cpanel::CargoBigCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => cargo_big_category.to_param}, valid_session
      }.to change(Cpanel::CargoBigCategory, :count).by(-1)
    end

    it "redirects to the cpanel_cargo_big_categories list" do
      cargo_big_category = Cpanel::CargoBigCategory.create! valid_attributes
      delete :destroy, {:id => cargo_big_category.to_param}, valid_session
      response.should redirect_to(cpanel_cargo_big_categories_url)
    end
  end

end
