source 'http://ruby.taobao.org'

gem 'rails', '3.2.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'



# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

require 'pathname'
pn = Pathname.new(File.dirname(__FILE__))
w090_path=pn.parent #do we have one line solution?
vob_path=pn.parent.parent#do we have one line solution?
gem "rforum" ,:path=>File.join(w090_path,"Rforum") 
gem "rtheme" ,:path=>File.join(w090_path,"Rtheme")
gem "ruser" ,:path=>File.join(w090_path,"Ruser")
gem "rcity" ,:path=>File.join(w090_path,"Rcity")
gem "rcargo" ,:path=>File.join(w090_path,"Rcargo")
gem "rtruck" ,:path=>File.join(w090_path,"Rtruck")
gem "rcompany" ,:path=>File.join(w090_path,"Rcompany")
#include some special gem in github
#gem 'bootstrap-rails', :require => 'bootstrap-rails', :path => '~/vob/github/bootstrap-rails'
gem 'mail_view', :path => "~/vob/github/mail_view"
gem 'quiet_assets', :path => '~/vob/github/quiet_assets'
gem 'simple_form', :path => '~/vob/github/simple_form'
gem 'grape',  :path => '~/vob/github/grape'

# why add dependency not work ,add here as workaround
gem 'bson_ext'


